# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13video_service.proto\x12\x04main\"\x1f\n\x0cVideoRequest\x12\x0f\n\x07videoId\x18\x01 \x01(\t\"\x1f\n\rVideoResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x32G\n\x0cVideoService\x12\x37\n\nCheckVideo\x12\x12.main.VideoRequest\x1a\x13.main.VideoResponse\"\x00\x42\tZ\x07./;mainb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007./;main'
  _globals['_VIDEOREQUEST']._serialized_start=29
  _globals['_VIDEOREQUEST']._serialized_end=60
  _globals['_VIDEORESPONSE']._serialized_start=62
  _globals['_VIDEORESPONSE']._serialized_end=93
  _globals['_VIDEOSERVICE']._serialized_start=95
  _globals['_VIDEOSERVICE']._serialized_end=166
# @@protoc_insertion_point(module_scope)
